SMC Template Class 1.0: smc::historyelement< Particle > Class Template Reference
smc::historyelement< Particle > Class Template Reference
A template class for the elements of a linked list to be used for the history of the sampler.
#include <history.hh>
Public Member Functions
historyelement ()
The null constructor creates an empty history element.
historyelement (long lNumber, Particle *pNew, int nAccepts, historyflags hf)
A constructor with four arguments initialises the particle set.
historyelement (long lNumber, Particle *pNew, historyelement< Particle > *pParent, historyelement< Particle > *pChild, int nAccepts, historyflags hf)
A constructor with six arguments initialises the whole structure.
~historyelement ()
The destructor tidies up.
double GetESS (void) const
Returns the effective sample size of this particle generation.
historyflags GetFlags (void) const
Returns the flags.
historyelement< Particle > * GetLast (void) const
Returns the parent of this element.
historyelement< Particle > * GetNext (void) const
Returns the child of this element.
long GetNumber (void) const
Returns the number of particles present.
Particle * GetValues (void) const
Returns a pointer to the current particle set.
void InsertAfter (long lNumber, Particle *pNew)
Add a new history element with the specified values after the current one and maintain the list structure.
long double Integrate (long lTime, double(*pIntegrand)(long, const Particle &, void *), void *pAuxiliary)
Integrate the supplied function according to the empirical measure of the particle ensemble.
void SetLast (historyelement< Particle > *pParent)
Sets the elements parent.
void SetNext (historyelement< Particle > *pChild)
Sets the elements child.
void SetValue (long lNumber, Particle *pNew)
Sets the particle set to the specified values.
int AcceptCount (void)
Returns the number of MCMC moves accepted during this iteration.
int WasResampled (void)
Returns true if the particle set.
historyelement< Particle > operator<< (unsigned long ulCount)
The left shift operator returns the element a number of positions prior to this one.
historyelement< Particle > operator>> (unsigned long ulCount)
The right shift operator returns the element a number of positions after this one.
Private Attributes
long number
The number of particles (presently redundant as this is not a function of iteration)
int nAccepted
Number of MCMC moves accepted during this iteration.
Particle * value
The particles themselves (values and weights)
historyflags flags
Flags associated with this iteration.
historyelement< Particle > * pLast
The parent of this node.
historyelement< Particle > * pNext
The child of this node.
Detailed Description
template<class Particle>
class smc::historyelement< Particle >
A template class for the elements of a linked list to be used for the history of the sampler.
Definition at line 46 of file history.hh.
Constructor & Destructor Documentation
historyelement() [1/3]
template<class Particle > smc::historyelement< Particle >::historyelement
The null constructor creates an empty history element.
Definition at line 122 of file history.hh.
historyelement() [2/3]
template<class Particle > smc::historyelement< Particle >::historyelement (long lNumber, Particle * pNew, int nAccepts, historyflags hf)
A constructor with four arguments initialises the particle set.
Parameters
lNumber The number of particles present in the particle generation
pNew The array of particles which are present in the particle generation
nAccepts The number of MCMC moves that were accepted during this particle generation
hf The historyflags associated with the particle generation
Definition at line 138 of file history.hh.
historyelement() [3/3]
template<class Particle > smc::historyelement< Particle >::historyelement (long lNumber, Particle * pNew, historyelement< Particle > * pParent, historyelement< Particle > * pChild, int nAccepts, historyflags hf)
A constructor with six arguments initialises the whole structure.
Parameters
lNumber The number of particles present in the particle generation
pNew The array of particles which are present in the particle generation
pParent A pointer to the previous particle generation
pChild A pointer to the next particle generation
nAccepts The number of MCMC moves that were accepted during this particle generation
hf The historyflags associated with the particle generation
Definition at line 158 of file history.hh.
~historyelement()
template<class Particle > smc::historyelement< Particle >::~historyelement
The destructor tidies up.
Definition at line 174 of file history.hh.
Member Function Documentation
AcceptCount()
template<class Particle > int smc::historyelement< Particle >::AcceptCount (void) inline
Returns the number of MCMC moves accepted during this iteration.
Definition at line 91 of file history.hh.
Referenced by smc::history< smc::particle< Space > >::OstreamMCMCRecordToStream(), and smc::history< smc::particle< Space > >::Pop().
GetESS()
template<class Particle > double smc::historyelement< Particle >::GetESS (void) const
Returns the effective sample size of this particle generation.
Definition at line 181 of file history.hh.
Referenced by smc::history< smc::particle< Space > >::GetESS(), and smc::history< smc::particle< Space > >::OstreamResamplingRecordToStream().
GetFlags()
template<class Particle > historyflags smc::historyelement< Particle >::GetFlags (void) const inline
Returns the flags.
Definition at line 70 of file history.hh.
Referenced by smc::history< smc::particle< Space > >::Pop().
GetLast()
template<class Particle > historyelement<Particle>* smc::historyelement< Particle >::GetLast (void) const inline
Returns the parent of this element.
Definition at line 72 of file history.hh.
Referenced by smc::history< smc::particle< Space > >::Pop(), and smc::history< smc::particle< Space > >::Push().
GetNext()
template<class Particle > historyelement<Particle>* smc::historyelement< Particle >::GetNext (void) const inline
Returns the child of this element.
Definition at line 74 of file history.hh.
Referenced by smc::history< smc::particle< Space > >::GetESS(), smc::history< smc::particle< Space > >::IntegratePathSampling(), smc::history< smc::particle< Space > >::OstreamMCMCRecordToStream(), smc::history< smc::particle< Space > >::OstreamResamplingRecordToStream(), and smc::history< smc::particle< Space > >::Pop().
GetNumber()
template<class Particle > long smc::historyelement< Particle >::GetNumber (void) const inline
Returns the number of particles present.
Definition at line 76 of file history.hh.
Referenced by smc::history< smc::particle< Space > >::Pop().
GetValues()
template<class Particle > Particle* smc::historyelement< Particle >::GetValues (void) const inline
Returns a pointer to the current particle set.
Definition at line 78 of file history.hh.
Referenced by smc::history< smc::particle< Space > >::Pop().
InsertAfter()
template<class Particle > void smc::historyelement< Particle >::InsertAfter (long lNumber, Particle * pNew)
Add a new history element with the specified values after the current one and maintain the list structure.
Parameters
lNumber The number of particles in the generation to be inserted
pNew The value of the particle generation to be inserted
Definition at line 219 of file history.hh.
Integrate()
template<class Particle > long double smc::historyelement< Particle >::Integrate (long lTime, double(*)(long, const Particle &, void *) pIntegrand, void * pAuxiliary)
Integrate the supplied function according to the empirical measure of the particle ensemble.
Parameters
lTime The timestep at which the integration is to be carried out
pIntegrand The function which is to be integrated
pAuxiliary A pointer to additional information which is passed to the integrand function
Definition at line 198 of file history.hh.
Referenced by smc::history< smc::particle< Space > >::IntegratePathSampling(), and smc::history< smc::particle< Space > >::IntegratePathSamplingFinalStep().
operator<<()
template<class Particle > historyelement<Particle> smc::historyelement< Particle >::operator<< (unsigned long ulCount) inline
The left shift operator returns the element a number of positions prior to this one.
Parameters
ulCount The number of positions by which to shift.
Returns
The element a number of positions before this one.
Definition at line 99 of file history.hh.
operator>>()
template<class Particle > historyelement<Particle> smc::historyelement< Particle >::operator>> (unsigned long ulCount) inline
The right shift operator returns the element a number of positions after this one.
Parameters
ulCount The number of positions by which to shift.
Returns
The right shift operator returns the element a number of positions after this one.
Definition at line 111 of file history.hh.
SetLast()
template<class Particle > void smc::historyelement< Particle >::SetLast (historyelement< Particle > * pParent) inline
Sets the elements parent.
Definition at line 84 of file history.hh.
SetNext()
template<class Particle > void smc::historyelement< Particle >::SetNext (historyelement< Particle > * pChild) inline
Sets the elements child.
Definition at line 86 of file history.hh.
Referenced by smc::history< smc::particle< Space > >::Pop().
SetValue()
template<class Particle > void smc::historyelement< Particle >::SetValue (long lNumber, Particle * pNew)
Sets the particle set to the specified values.
WasResampled()
template<class Particle > int smc::historyelement< Particle >::WasResampled (void) inline
Returns true if the particle set.
Definition at line 93 of file history.hh.
Referenced by smc::history< smc::particle< Space > >::OstreamResamplingRecordToStream().
Member Data Documentation
flags
template<class Particle > historyflags smc::historyelement< Particle >::flags private
Flags associated with this iteration.
Definition at line 52 of file history.hh.
Referenced by smc::historyelement< smc::particle< Space > >::GetFlags(), and smc::historyelement< smc::particle< Space > >::WasResampled().
nAccepted
template<class Particle > int smc::historyelement< Particle >::nAccepted private
Number of MCMC moves accepted during this iteration.
Definition at line 50 of file history.hh.
Referenced by smc::historyelement< smc::particle< Space > >::AcceptCount().
number
template<class Particle > long smc::historyelement< Particle >::number private
The number of particles (presently redundant as this is not a function of iteration)
Definition at line 49 of file history.hh.
Referenced by smc::historyelement< smc::particle< Space > >::GetNumber().
pLast
template<class Particle > historyelement<Particle>* smc::historyelement< Particle >::pLast private
The parent of this node.
Definition at line 53 of file history.hh.
Referenced by smc::historyelement< smc::particle< Space > >::GetLast(), and smc::historyelement< smc::particle< Space > >::SetLast().
pNext
template<class Particle > historyelement<Particle>* smc::historyelement< Particle >::pNext private
The child of this node.
Definition at line 54 of file history.hh.
Referenced by smc::historyelement< smc::particle< Space > >::GetNext(), and smc::historyelement< smc::particle< Space > >::SetNext().
value
template<class Particle > Particle* smc::historyelement< Particle >::value private
The particles themselves (values and weights)
Definition at line 51 of file history.hh.
Referenced by smc::historyelement< smc::particle< Space > >::GetValues().
The documentation for this class was generated from the following file:
include/history.hh