SMC Template Class 1.0: smc::history< Particle > Class Template Reference
smc::history< Particle > Class Template Reference
A template class for the history associated with a particle system evolving in SMC.
#include <history.hh>
Public Member Functions
history ()
The argument free constructor creates an empty list.
const historyelement< Particle > * GetElement (void) const
This function returns a pointer to the first element of the history.
double GetESS (long lGeneration) const
Returns the effective sample size of the specified particle generation.
long GetLength (void) const
Returns the number of generations recorded within the history.
double IntegratePathSampling (double(*pIntegrand)(long, const Particle &, void *), double(*pWidth)(long, void *), void *pAuxiliary)
Integrate the supplied function over the path of the particle ensemble.
double IntegratePathSamplingFinalStep (double(*pIntegrand)(long, const Particle &, void *), void *pAuxiliary) const
void OstreamMCMCRecordToStream (std::ostream &os) const
Output a vector indicating the number of accepted MCMC moves at each time instance.
void OstreamResamplingRecordToStream (std::ostream &os) const
Output a 0-1 value vector indicating the times at which resampling occured to an output stream.
Particle * Pop (void)
Remove the terminal particle generation from the list and return that particle.
void Pop (long *plNumber, Particle **ppNew, int *pnAccept, historyflags *phf)
Remove the terminal particle generation from the list and stick it in the supplied data structures.
void Push (long lNumber, Particle *pNew, int nAccept, historyflags hf)
Append the supplied particle generation to the end of the list.
Private Attributes
long lLength
The length of the history in time steps.
historyelement< Particle > * pRoot
The first time step.
historyelement< Particle > * pLeaf
The most recent time step.
Detailed Description
template<class Particle>
class smc::history< Particle >
A template class for the history associated with a particle system evolving in SMC.
The history is a template class which should have an associated class type corresponding to a particle of the desired type, not the type itself.
Essentially, this is implemented as a doubly linked list.
Definition at line 232 of file history.hh.
Constructor & Destructor Documentation
history()
template<class Particle > smc::history< Particle >::history
The argument free constructor creates an empty list.
This constructor simply sets the root and leaf pointers to NULL and the list length to zero.
Definition at line 276 of file history.hh.
Member Function Documentation
GetElement()
template<class Particle > const historyelement<Particle >* smc::history< Particle >::GetElement (void) const inline
This function returns a pointer to the first element of the history.
Definition at line 247 of file history.hh.
GetESS()
template<class Particle > double smc::history< Particle >::GetESS (long lGeneration) const
Returns the effective sample size of the specified particle generation.
Definition at line 284 of file history.hh.
GetLength()
template<class Particle > long smc::history< Particle >::GetLength (void) const inline
Returns the number of generations recorded within the history.
Definition at line 252 of file history.hh.
IntegratePathSampling()
template<class Particle > double smc::history< Particle >::IntegratePathSampling (double(*)(long, const Particle &, void *) pIntegrand, double(*)(long, void *) pWidth, void * pAuxiliary)
Integrate the supplied function over the path of the particle ensemble.
This function performs a trapezoidal integration of the type which is useful when using path sampling to estimate the normalising constant of a potential function in those cases where a sequence of distributions is produced by deforming the initial distribution by a sequence of progressively more influential potential functions which are proportional to the density of some other distribution with respect to the starting distribution.
The integrand is integrated at every time point in the particle system history. The results of this integration are taken to be point-evaluations of the path sampling integrand which are spaced on a grid of intervals given by the width function. The path sampling integral is then calculated by performing a suitable trapezoidal integration and the results of this integration is returned.
pAuxiliary is passed to both of the user specified functions to allow the user to pass additional data to either or both of these functions in a convenient manner. It is safe to use NULL if no such data is used by either function.
Parameters
pIntegrand The function to integrated. The first argument is evolution time, the second a particle at which the function is to be evaluated and the final argument is always pAuxiliary.
pWidth The function which returns the width of the path sampling grid at the specified evolution time. The final argument is always pAuxiliary
pAuxiliary A pointer to auxiliary data to pass to both of the above functions
Definition at line 347 of file history.hh.
Referenced by smc::sampler< Space >::IntegratePathSampling().
IntegratePathSamplingFinalStep()
template<class Particle > double smc::history< Particle >::IntegratePathSamplingFinalStep (double(*)(long, const Particle &, void *) pIntegrand, void * pAuxiliary) const
Definition at line 366 of file history.hh.
OstreamMCMCRecordToStream()
template<class Particle > void smc::history< Particle >::OstreamMCMCRecordToStream (std::ostream & os) const
Output a vector indicating the number of accepted MCMC moves at each time instance.
This function records the MCMC acceptance history to the specified output stream as a list of the number of moves accepted at each time instant.
Parameters
os The output stream to send the data to.
Definition at line 299 of file history.hh.
OstreamResamplingRecordToStream()
template<class Particle > void smc::history< Particle >::OstreamResamplingRecordToStream (std::ostream & os) const
Output a 0-1 value vector indicating the times at which resampling occured to an output stream.
This function records the resampling history to the specified output stream as a 0-1 valued list which takes the value 1 for those time instances when resampling occured and 0 otherwise.
Parameters
os The output stream to send the data to.
Definition at line 313 of file history.hh.
Pop() [1/2]
template<class Particle > void smc::history< Particle >::Pop (long * plNumber, Particle ** ppNew, int * pnAccept, historyflags * phf)
Remove the terminal particle generation from the list and stick it in the supplied data structures.
Pop operates as the usual stack operation
If called with four pointers of this sort, it removes the last particle generation from the history stack and places them in the reference objects.
Definition at line 400 of file history.hh.
Pop() [2/2]
template<class Particle > Particle * smc::history< Particle >::Pop (void)
Remove the terminal particle generation from the list and return that particle.
Pop() operates just as the standard stack operation does. It removes the particle generation currently occupying the terminal position in the chain, decrements the length counter and returns the particle set as an array.
Definition at line 375 of file history.hh.
Referenced by smc::sampler< Space >::Initialise(), smc::sampler< Space >::IntegratePathSampling(), and smc::sampler< Space >::IterateBack().
Push()
template<class Particle > void smc::history< Particle >::Push (long lNumber, Particle * pNew, int nAccepts, historyflags hf)
Append the supplied particle generation to the end of the list.
Push operates just like the standard stack operation: it adds the specified particle set generation to the history of the particle set and increments the stack counter.
Parameters
lNumber The number of particles present in this generation of the system.
pNew An array containing the particles present in this generation of the system.
nAccepts The number of accepted MCMC moves during this iteration of the system
hf The historyflags associated with this generation of the system.
Definition at line 439 of file history.hh.
Referenced by smc::sampler< Space >::Initialise(), smc::sampler< Space >::IntegratePathSampling(), and smc::sampler< Space >::IterateEss().
Member Data Documentation
lLength
template<class Particle > long smc::history< Particle >::lLength private
The length of the history in time steps.
Definition at line 236 of file history.hh.
pLeaf
template<class Particle > historyelement<Particle>* smc::history< Particle >::pLeaf private
The most recent time step.
Definition at line 240 of file history.hh.
pRoot
template<class Particle > historyelement<Particle>* smc::history< Particle >::pRoot private
The first time step.
Definition at line 238 of file history.hh.
The documentation for this class was generated from the following file:
include/history.hh