SMC Template Class 1.0: smc::moveset< Space > Class Template Reference
smc::moveset< Space > Class Template Reference
A template class for a set of moves for use in an SMC samplers framework.
#include <moveset.hh>
Public Member Functions
moveset ()
Create a completely unspecified moveset.
moveset (particle< Space >(*pfInit)(rng *), void(*pfNewMoves)(long, particle< Space > &, rng *), int(*pfNewMCMC)(long, particle< Space > &, rng *))
Create a reduced moveset with a single move.
moveset (particle< Space >(*pfInit)(rng *), long(*pfMoveSelector)(long, const particle< Space > &, rng *), long nMoves, void(**pfNewMoves)(long, particle< Space > &, rng *), int(*pfNewMCMC)(long, particle< Space > &, rng *))
Create a fully specified moveset.
particle< Space > DoInit (rng *pRng)
Initialise a particle.
int DoMCMC (long lTime, particle< Space > &pFrom, rng *pRng)
Perform an MCMC move on a particle.
void DoMove (long lTime, particle< Space > &pFrom, rng *pRng)
Select an appropriate move at time lTime and apply it to pFrom.
~moveset ()
Free the memory used for the array of move pointers when deleting.
void SetInitialisor (particle< Space >(*pfInit)(rng *))
Set the initialisation function.
void SetMCMCFunction (int(*pfNewMCMC)(long, particle< Space > &, rng *))
Set the MCMC function.
void SetMoveSelectionFunction (long(*pfMoveSelectNew)(long, const particle< Space > &, rng *))
Set the move selection function.
void SetMoveFunctions (long nMoves, void(**pfNewMoves)(long, particle< Space > &, rng *))
Set the individual move functions to the supplied array of such functions.
moveset< Space > & operator= (moveset< Space > &pFrom)
Moveset assignment should allocate buffers and deep copy all members.
Private Attributes
long number
The number of moves which are present in the set.
particle< Space >(* pfInitialise)(rng *)
The function which initialises a particle.
long(* pfMoveSelect)(long, const particle< Space > &, rng *)
The function which selects a move for a given particle at a given time.
void(** pfMoves)(long, particle< Space > &, rng *)
The functions which perform actual moves.
int(* pfMCMC)(long, particle< Space > &, rng *)
A Markov Chain Monte Carlo move.
Detailed Description
template<class Space>
class smc::moveset< Space >
A template class for a set of moves for use in an SMC samplers framework.
Definition at line 36 of file moveset.hh.
Constructor & Destructor Documentation
moveset() [1/3]
template<class Space > smc::moveset< Space >::moveset
Create a completely unspecified moveset.
The argument free smc::moveset constructor simply sets the number of available moves to zero and sets all of the associated function pointers to NULL.
Definition at line 97 of file moveset.hh.
moveset() [2/3]
template<class Space > smc::moveset< Space >::moveset (particle< Space >(*)(rng *) pfInit, void(*)(long, particle< Space > &, rng *) pfNewMoves, int(*)(long, particle< Space > &, rng *) pfNewMCMC)
Create a reduced moveset with a single move.
The three argument moveset constructor creates a new set of moves and sets all of the relevant function pointers to the supplied values. Only a single move should exist if this constructor is used.
Parameters
pfInit The function which should be used to initialise particles when the system is initialised
pfNewMoves An functions which moves a particle at a specified time to a new location
pfNewMCMC The function which should be called to apply an MCMC move (if any)
Definition at line 113 of file moveset.hh.
moveset() [3/3]
template<class Space > smc::moveset< Space >::moveset (particle< Space >(*)(rng *) pfInit, long(*)(long, const particle< Space > &, rng *) pfMoveSelector, long nMoves, void(**)(long, particle< Space > &, rng *) pfNewMoves, int(*)(long, particle< Space > &, rng *) pfNewMCMC)
Create a fully specified moveset.
The five argument moveset constructor creates a new set of moves and sets all of the relevant function pointers to the supplied values.
Parameters
pfInit The function which should be used to initialise particles when the system is initialised
pfMoveSelector The function which selects a move to apply, at a specified time, to a specified particle
nMoves The number of moves which are defined in general
pfNewMoves An array of functions which move a particle at a specified time to a new location
pfNewMCMC The function which should be called to apply an MCMC move (if any)
Definition at line 132 of file moveset.hh.
~moveset()
template<class Space > smc::moveset< Space >::~moveset
Free the memory used for the array of move pointers when deleting.
Definition at line 144 of file moveset.hh.
Member Function Documentation
DoInit()
template<class Space > particle<Space> smc::moveset< Space >::DoInit (rng * pRng) inline
Initialise a particle.
Definition at line 63 of file moveset.hh.
References smc::moveset< Space >::pfInitialise.
Referenced by smc::sampler< Space >::Initialise().
DoMCMC()
template<class Space > int smc::moveset< Space >::DoMCMC (long lTime, particle< Space > & pFrom, rng * pRng)
Perform an MCMC move on a particle.
Definition at line 151 of file moveset.hh.
Referenced by smc::sampler< Space >::IterateEss().
DoMove()
template<class Space > void smc::moveset< Space >::DoMove (long lTime, particle< Space > & pFrom, rng * pRng)
Select an appropriate move at time lTime and apply it to pFrom.
Definition at line 162 of file moveset.hh.
Referenced by smc::sampler< Space >::MoveParticles().
operator=()
template<class Space > moveset< Space > & smc::moveset< Space >::operator= (moveset< Space > & pFrom)
Moveset assignment should allocate buffers and deep copy all members.
Definition at line 189 of file moveset.hh.
References smc::moveset< Space >::number, smc::moveset< Space >::pfInitialise, smc::moveset< Space >::pfMCMC, smc::moveset< Space >::pfMoves, and smc::moveset< Space >::pfMoveSelect.
SetInitialisor()
template<class Space > void smc::moveset< Space >::SetInitialisor (particle< Space >(*)(rng *) pfInit) inline
Set the initialisation function.
Parameters
pfInit is a function which returns a particle generated according to the initial distribution
Definition at line 74 of file moveset.hh.
References smc::moveset< Space >::pfInitialise.
SetMCMCFunction()
template<class Space > void smc::moveset< Space >::SetMCMCFunction (int(*)(long, particle< Space > &, rng *) pfNewMCMC) inline
Set the MCMC function.
Parameters
pfNewMCMC The function which performs an MCMC move
Definition at line 79 of file moveset.hh.
References smc::moveset< Space >::pfMCMC.
SetMoveFunctions()
template<class Space > void smc::moveset< Space >::SetMoveFunctions (long nMoves, void(**)(long, particle< Space > &, rng *) pfNewMoves)
Set the individual move functions to the supplied array of such functions.
Parameters
nMoves The number of moves which are defined in general.
pfNewMoves An array of functions which move a particle at a specified time to a new location
The move functions accept two arguments, the first of which corresponds to the system evolution time and the second to an initial particle position and the second to a weighted starting position. It returns a new weighted position corresponding to the moved particle.
Definition at line 177 of file moveset.hh.
SetMoveSelectionFunction()
template<class Space > void smc::moveset< Space >::SetMoveSelectionFunction (long(*)(long, const particle< Space > &, rng *) pfMoveSelectNew) inline
Set the move selection function.
Parameters
pfMoveSelectNew returns the index of move to perform at the specified time given a specified particle
Definition at line 83 of file moveset.hh.
References smc::moveset< Space >::pfMoveSelect.
Member Data Documentation
number
template<class Space > long smc::moveset< Space >::number private
The number of moves which are present in the set.
Definition at line 40 of file moveset.hh.
Referenced by smc::moveset< Space >::operator=().
pfInitialise
template<class Space > particle<Space>(* smc::moveset< Space >::pfInitialise) (rng *) private
The function which initialises a particle.
Definition at line 42 of file moveset.hh.
Referenced by smc::moveset< Space >::DoInit(), smc::moveset< Space >::operator=(), and smc::moveset< Space >::SetInitialisor().
pfMCMC
template<class Space > int(* smc::moveset< Space >::pfMCMC) (long, particle< Space > &, rng *) private
A Markov Chain Monte Carlo move.
Definition at line 48 of file moveset.hh.
Referenced by smc::moveset< Space >::operator=(), and smc::moveset< Space >::SetMCMCFunction().
pfMoves
template<class Space > void(** smc::moveset< Space >::pfMoves) (long, particle< Space > &, rng *) private
The functions which perform actual moves.
Definition at line 46 of file moveset.hh.
Referenced by smc::moveset< Space >::operator=().
pfMoveSelect
template<class Space > long(* smc::moveset< Space >::pfMoveSelect) (long, const particle< Space > &, rng *) private
The function which selects a move for a given particle at a given time.
Definition at line 44 of file moveset.hh.
Referenced by smc::moveset< Space >::operator=(), and smc::moveset< Space >::SetMoveSelectionFunction().
The documentation for this class was generated from the following file:
include/moveset.hh