SMC Template Class 1.0: smc::sampler< Space > Class Template Reference
smc::sampler< Space > Class Template Reference
A template class for an interacting particle system suitable for SMC sampling.
#include <sampler.hh>
Public Member Functions
sampler (long lSize, HistoryType htHistoryMode)
Create an particle system containing lSize uninitialised particles with the specified mode.
sampler (long lSize, HistoryType htHistoryMode, const gsl_rng_type *rngType, unsigned long nSeed)
Create an particle system constaining lSize uninitialised particles with the specified mode and random number generator.
~sampler ()
Dispose of a sampler.
double GetESS (void) const
Calculates and Returns the Effective Sample Size.
const history< particle< Space > > * GetHistory (void) const
Returns a pointer to the History of the particle system.
long GetNumber (void) const
Returns the number of particles within the system.
const Space & GetParticleValue (int n)
Return the value of particle n.
double GetParticleLogWeight (int n)
Return the logarithmic unnormalized weight of particle n.
double GetParticleWeight (int n)
Return the unnormalized weight of particle n.
long GetTime (void) const
Returns the current evolution time of the system.
void Initialise (void)
Initialise the sampler and its constituent particles.
double Integrate (double(*pIntegrand)(const Space &, void *), void *pAuxiliary)
Integrate the supplied function with respect to the current particle set.
double IntegratePathSampling (double(*pIntegrand)(long, const particle< Space > &, void *), double(*pWidth)(long, void *), void *pAuxiliary)
Integrate the supplied function over the path path using the supplied width function.
void Iterate (void)
Perform one iteration of the simulation algorithm.
void IterateBack (void)
Cancel one iteration of the simulation algorithm.
double IterateEss (void)
Perform one iteration of the simulation algorithm and return the resulting ess.
void IterateUntil (long lTerminate)
Perform iterations until the specified evolution time is reached.
void MoveParticles (void)
Move the particle set by proposing an applying an appropriate move to each particle.
void Resample (ResampleType lMode)
Resample the particle set using the specified resmpling scheme.
void SetMoveSet (moveset< Space > &pNewMoveset)
Sets the entire moveset to the one which is supplied.
void SetResampleParams (ResampleType rtMode, double dThreshold)
Set Resampling Parameters.
std::ostream & StreamParticle (std::ostream &os, long n)
Dump a specified particle to the specified output stream in a human readable form.
std::ostream & StreamParticles (std::ostream &os)
Dump the entire particle set to the specified output stream in a human readable form.
Private Member Functions
sampler (const sampler< Space > &sFrom)
Duplication of smc::sampler is not currently permitted.
sampler< Space > & operator= (const sampler< Space > &sFrom)
Duplication of smc::sampler is not currently permitted.
Private Attributes
rng * pRng
A random number generator.
long N
Number of particles in the system.
long T
The current evolution time of the system.
ResampleType rtResampleMode
The resampling mode which is to be employed.
double dResampleThreshold
The effective sample size at which resampling should be used.
double * dRSWeights
Structure used internally for resampling.
unsigned int * uRSCount
Structure used internally for resampling.
unsigned int * uRSIndices
Structure used internally for resampling.
particle< Space > * pParticles
The particles within the system.
moveset< Space > Moves
The set of moves available.
int nAccepted
The number of MCMC moves which have been accepted during this iteration.
int nResampled
A flag which tracks whether the ensemble was resampled during this iteration.
HistoryType htHistoryMode
A mode flag which indicates whether historical information is stored.
history< particle< Space > > History
The historical process associated with the particle system.
Detailed Description
template<class Space>
class smc::sampler< Space >
A template class for an interacting particle system suitable for SMC sampling.
Definition at line 53 of file sampler.hh.
Constructor & Destructor Documentation
sampler() [1/3]
template<class Space > smc::sampler< Space >::sampler (long lSize, HistoryType htHM)
Create an particle system containing lSize uninitialised particles with the specified mode.
The constructor prepares a sampler for use but does not assign any moves to the moveset, initialise the particles or otherwise perform any sampling related tasks. Its main function is to allocate a region of memory in which to store the particle set and to initialise a random number generator.
Parameters
lSize The number of particles present in the ensemble (at time 0 if this is a variable quantity)
htHM The history mode to use: set this to SMC_HISTORY_RAM to store the whole history of the system and SMC_HISTORY_NONE to avoid doing so.
Template Parameters
Space The class used to represent a point in the sample space.
Structure used internally for resampling.
Structure used internally for resampling.
Definition at line 156 of file sampler.hh.
References SMC_RESAMPLE_STRATIFIED.
sampler() [2/3]
template<class Space > smc::sampler< Space >::sampler (long lSize, HistoryType htHM, const gsl_rng_type * rngType, unsigned long rngSeed)
Create an particle system constaining lSize uninitialised particles with the specified mode and random number generator.
The constructor prepares a sampler for use but does not assign any moves to the moveset, initialise the particles or otherwise perform any sampling related tasks. Its main function is to allocate a region of memory in which to store the particle set and to initialise a random number generator.
Parameters
lSize The number of particles present in the ensemble (at time 0 if this is a variable quantity)
htHM The history mode to use: set this to SMC_HISTORY_RAM to store the whole history of the system and SMC_HISTORY_NONE to avoid doing so.
rngType The type of random number generator to use
rngSeed The seed to use for the random number generator
Template Parameters
Space The class used to represent a point in the sample space.
Structure used internally for resampling.
Structure used internally for resampling.
Definition at line 185 of file sampler.hh.
References SMC_HISTORY_RAM, and SMC_RESAMPLE_STRATIFIED.
~sampler()
template<class Space > smc::sampler< Space >::~sampler
Dispose of a sampler.
Definition at line 206 of file sampler.hh.
sampler() [3/3]
template<class Space > smc::sampler< Space >::sampler (const sampler< Space > & sFrom) private
Duplication of smc::sampler is not currently permitted.
Allow a human readable version of the sampler configuration to be produced using the stream operator. std::ostream & operator<< (std::ostream& os, sampler<Space> & s);
Member Function Documentation
GetESS()
template<class Space > double smc::sampler< Space >::GetESS (void) const
Calculates and Returns the Effective Sample Size.
Definition at line 219 of file sampler.hh.
GetHistory()
template<class Space > const history<particle<Space> >* smc::sampler< Space >::GetHistory (void) const inline
Returns a pointer to the History of the particle system.
Definition at line 100 of file sampler.hh.
References smc::sampler< Space >::History.
GetNumber()
template<class Space > long smc::sampler< Space >::GetNumber (void) const inline
Returns the number of particles within the system.
Definition at line 102 of file sampler.hh.
References smc::sampler< Space >::N.
Referenced by std::operator<<().
GetParticleLogWeight()
template<class Space > double smc::sampler< Space >::GetParticleLogWeight (int n) inline
Return the logarithmic unnormalized weight of particle n.
Definition at line 106 of file sampler.hh.
References smc::sampler< Space >::pParticles.
GetParticleValue()
template<class Space > const Space& smc::sampler< Space >::GetParticleValue (int n) inline
Return the value of particle n.
Definition at line 104 of file sampler.hh.
References smc::sampler< Space >::pParticles.
GetParticleWeight()
template<class Space > double smc::sampler< Space >::GetParticleWeight (int n) inline
Return the unnormalized weight of particle n.
Definition at line 108 of file sampler.hh.
References smc::sampler< Space >::pParticles.
GetTime()
template<class Space > long smc::sampler< Space >::GetTime (void) const inline
Returns the current evolution time of the system.
Definition at line 110 of file sampler.hh.
References smc::sampler< Space >::T.
Referenced by std::operator<<().
Initialise()
template<class Space > void smc::sampler< Space >::Initialise (void)
Initialise the sampler and its constituent particles.
At present this function resets the system evolution time to 0 and calls the moveset initialisor to assign each particle in the ensemble.
Note that the initialisation function must be specified before calling this function.
Definition at line 238 of file sampler.hh.
References smc::moveset< Space >::DoInit(), smc::history< Particle >::Pop(), smc::history< Particle >::Push(), and SMC_HISTORY_NONE.
Integrate()
template<class Space > double smc::sampler< Space >::Integrate (double(*)(const Space &, void *) pIntegrand, void * pAuxiliary)
Integrate the supplied function with respect to the current particle set.
This function returns the result of integrating the supplied function under the empirical measure associated with the particle set at the present time. The final argument of the integrand function is a pointer which will be supplied with pAuxiliary to allow for arbitrary additional information to be passed to the function being integrated.
Parameters
pIntegrand The function to integrate with respect to the particle set
pAuxiliary A pointer to any auxiliary data which should be passed to the function
Definition at line 262 of file sampler.hh.
IntegratePathSampling()
template<class Space > double smc::sampler< Space >::IntegratePathSampling (double(*)(long, const particle< Space > &, void *) pIntegrand, double(*)(long, void *) pWidth, void * pAuxiliary)
Integrate the supplied function over the path path using the supplied width function.
This function is intended to be used to estimate integrals of the sort which must be evaluated to determine the normalising constant of a distribution obtain using a sequence of potential functions proportional to densities with respect to the initial distribution to define a sequence of distributions leading up to the terminal, interesting distribution.
In this context, the particle set at each time is used to make an estimate of the path sampling integrand, and a trapezoidal integration is then performed to obtain an estimate of the path sampling integral which is the natural logarithm of the ratio of normalising densities.
Parameters
pIntegrand The quantity which we wish to integrate at each time
pWidth A pointer to a function which specifies the width of each
Definition at line 288 of file sampler.hh.
References smc::history< Particle >::IntegratePathSampling(), smc::history< Particle >::Pop(), smc::history< Particle >::Push(), SMC_EXCEPTION, SMC_HISTORY_NONE, and SMCX_MISSING_HISTORY.
Iterate()
template<class Space > void smc::sampler< Space >::Iterate (void)
Perform one iteration of the simulation algorithm.
The iterate function:
appends the current particle set to the history if desired
moves the current particle set
checks the effective sample size and resamples if necessary
performs a mcmc step if required
increments the current evolution time
Definition at line 306 of file sampler.hh.
IterateBack()
template<class Space > void smc::sampler< Space >::IterateBack (void)
Cancel one iteration of the simulation algorithm.
Definition at line 313 of file sampler.hh.
References smc::history< Particle >::Pop(), SMC_EXCEPTION, SMC_HISTORY_NONE, and SMCX_MISSING_HISTORY.
IterateEss()
template<class Space > double smc::sampler< Space >::IterateEss (void)
Perform one iteration of the simulation algorithm and return the resulting ess.
Definition at line 324 of file sampler.hh.
References smc::moveset< Space >::DoMCMC(), smc::history< Particle >::Push(), and SMC_HISTORY_NONE.
IterateUntil()
template<class Space > void smc::sampler< Space >::IterateUntil (long lTerminate)
Perform iterations until the specified evolution time is reached.
Definition at line 364 of file sampler.hh.
MoveParticles()
template<class Space > void smc::sampler< Space >::MoveParticles (void)
Move the particle set by proposing an applying an appropriate move to each particle.
Definition at line 371 of file sampler.hh.
References smc::moveset< Space >::DoMove().
operator=()
template<class Space > sampler<Space>& smc::sampler< Space >::operator= (const sampler< Space > & sFrom) private
Duplication of smc::sampler is not currently permitted.
Resample()
template<class Space > void smc::sampler< Space >::Resample (ResampleType lMode)
Resample the particle set using the specified resmpling scheme.
Definition at line 380 of file sampler.hh.
References smc::particle< Space >::GetWeight(), smc::rng::Multinomial(), smc::particle< Space >::SetLogWeight(), smc::particle< Space >::SetValue(), SMC_RESAMPLE_MULTINOMIAL, SMC_RESAMPLE_RESIDUAL, SMC_RESAMPLE_STRATIFIED, SMC_RESAMPLE_SYSTEMATIC, and smc::rng::Uniform().
SetMoveSet()
template<class Space > void smc::sampler< Space >::SetMoveSet (moveset< Space > & pNewMoveset) inline
Sets the entire moveset to the one which is supplied.
Definition at line 130 of file sampler.hh.
References smc::sampler< Space >::Moves.
SetResampleParams()
template<class Space > void smc::sampler< Space >::SetResampleParams (ResampleType rtMode, double dThreshold)
Set Resampling Parameters.
This function configures the resampling parameters, allowing the specification of both the resampling mode and the threshold at which resampling is used.
Parameters
rtMode The resampling mode to be used.
dThreshold The threshold at which resampling is deemed necesary.
The rtMode parameter should be set to one of the following:
SMC_RESAMPLE_MULTINOMIAL to use multinomial resampling
SMC_RESAMPLE_RESIDUAL to use residual resampling
SMC_RESAMPLE_STRATIFIED to use stratified resampling
SMC_RESAMPLE_SYSTEMATIC to use systematic resampling
The dThreshold parameter can be set to a value in the range [0,1) corresponding to a fraction of the size of the particle set or it may be set to an integer corresponding to an actual effective sample size.
Definition at line 512 of file sampler.hh.
StreamParticle()
template<class Space > std::ostream & smc::sampler< Space >::StreamParticle (std::ostream & os, long n)
Dump a specified particle to the specified output stream in a human readable form.
Definition at line 522 of file sampler.hh.
StreamParticles()
template<class Space > std::ostream & smc::sampler< Space >::StreamParticles (std::ostream & os)
Dump the entire particle set to the specified output stream in a human readable form.
Definition at line 529 of file sampler.hh.
Referenced by std::operator<<().
Member Data Documentation
dResampleThreshold
template<class Space > double smc::sampler< Space >::dResampleThreshold private
The effective sample size at which resampling should be used.
Definition at line 67 of file sampler.hh.
dRSWeights
template<class Space > double* smc::sampler< Space >::dRSWeights private
Structure used internally for resampling.
Definition at line 69 of file sampler.hh.
History
template<class Space > history<particle<Space> > smc::sampler< Space >::History private
The historical process associated with the particle system.
Definition at line 88 of file sampler.hh.
Referenced by smc::sampler< Space >::GetHistory().
htHistoryMode
template<class Space > HistoryType smc::sampler< Space >::htHistoryMode private
A mode flag which indicates whether historical information is stored.
Definition at line 86 of file sampler.hh.
Moves
template<class Space > moveset<Space> smc::sampler< Space >::Moves private
The set of moves available.
Definition at line 78 of file sampler.hh.
Referenced by smc::sampler< Space >::SetMoveSet().
N
template<class Space > long smc::sampler< Space >::N private
Number of particles in the system.
Definition at line 60 of file sampler.hh.
Referenced by smc::sampler< Space >::GetNumber().
nAccepted
template<class Space > int smc::sampler< Space >::nAccepted private
The number of MCMC moves which have been accepted during this iteration.
Definition at line 81 of file sampler.hh.
nResampled
template<class Space > int smc::sampler< Space >::nResampled private
A flag which tracks whether the ensemble was resampled during this iteration.
Definition at line 83 of file sampler.hh.
pParticles
template<class Space > particle<Space>* smc::sampler< Space >::pParticles private
The particles within the system.
Definition at line 76 of file sampler.hh.
Referenced by smc::sampler< Space >::GetParticleLogWeight(), smc::sampler< Space >::GetParticleValue(), and smc::sampler< Space >::GetParticleWeight().
pRng
template<class Space > rng* smc::sampler< Space >::pRng private
A random number generator.
Definition at line 57 of file sampler.hh.
rtResampleMode
template<class Space > ResampleType smc::sampler< Space >::rtResampleMode private
The resampling mode which is to be employed.
Definition at line 65 of file sampler.hh.
T
template<class Space > long smc::sampler< Space >::T private
The current evolution time of the system.
Definition at line 62 of file sampler.hh.
Referenced by smc::sampler< Space >::GetTime().
uRSCount
template<class Space > unsigned int* smc::sampler< Space >::uRSCount private
Structure used internally for resampling.
Definition at line 71 of file sampler.hh.
uRSIndices
template<class Space > unsigned int* smc::sampler< Space >::uRSIndices private
Structure used internally for resampling.
Definition at line 73 of file sampler.hh.
The documentation for this class was generated from the following file:
include/sampler.hh