SMC Template Class 1.0: std Namespace Reference
std Namespace Reference
The standard namespace.
Functions
template<class Particle >
ostream & operator<< (ostream &os, smc::history< Particle > h)
This function will ultimately allow the standard stream operators to be used to display a particle history in a human readable form.
template<class Space >
std::ostream & operator<< (std::ostream &os, smc::particle< Space > &p)
Produce a human readable display of an smc::particle class using the standard stream operators.
template<class Space >
std::ostream & operator<< (std::ostream &os, smc::sampler< Space > &s)
Produce a human-readable display of the state of an smc::sampler class using the stream operator.
std::ostream & operator<< (std::ostream &, smc::exception &)
Produce a human-readable display of the state of an smc::exception class using the stream operator.
Detailed Description
The standard namespace.
The classes provided within the standard libraries reside within this namespace and the TDSMC class library adds a number of additional operator overloads to some of the standard classes to allow them to deal with our structures.
Function Documentation
operator<<() [1/4]
template<class Particle > ostream& std::operator<< (ostream & os, smc::history< Particle > h)
This function will ultimately allow the standard stream operators to be used to display a particle history in a human readable form.
It isn't yet fully implemented.
Definition at line 460 of file history.hh.
operator<<() [2/4]
std::ostream & std::operator<< (std::ostream & os, smc::exception & e)
Produce a human-readable display of the state of an smc::exception class using the stream operator.
Display a human-readable version of an SMC exception.
Produce a human-readable display of the state of an smc::exception class using the stream operator.
Parameters
os The output stream to which the display should be made.
e The exception which is to be displayed.
os The stream to write to.
e The exception class to display.
Returns
os
Definition at line 32 of file smc-exception.cc.
References smc::exception::lCode, smc::exception::lLine, smc::exception::szFile, and smc::exception::szMessage.
operator<<() [3/4]
template<class Space > std::ostream& std::operator<< (std::ostream & os, smc::particle< Space > & p)
Produce a human readable display of an smc::particle class using the standard stream operators.
Parameters
os The output stream to which the display should be made.
p The particle which is to be displayed.
Definition at line 141 of file particle.hh.
References smc::particle< Space >::GetLogWeight(), and smc::particle< Space >::GetValue().
operator<<() [4/4]
template<class Space > std::ostream& std::operator<< (std::ostream & os, smc::sampler< Space > & s)
Produce a human-readable display of the state of an smc::sampler class using the stream operator.
Parameters
os The output stream to which the display should be made.
s The sampler which is to be displayed.
Definition at line 546 of file sampler.hh.
References smc::sampler< Space >::GetNumber(), smc::sampler< Space >::GetTime(), and smc::sampler< Space >::StreamParticles().